/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lrr.login;

/**
 *
 * @author seo
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // 로그인 버튼 이벤트 연결 (GEN 코드 외부에서 처리)
        jButton1.addActionListener(this::handleLogin);
        // 플레이스홀더 설정
        setupPlaceholders();
        // 라디오버튼 그룹 설정 (하나만 선택 가능)
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(jRadioButton1); // 학생
        roleGroup.add(jRadioButton2); // 교수
        roleGroup.add(jRadioButton3); // 조교

        // 회원가입 버튼 이벤트 연결
        jButton2.addActionListener(e -> {
            new Register().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userId = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Lecture Room Reservation");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("USER Login");

        userId.setToolTipText("ID");
        userId.addActionListener(this::userIdActionPerformed);

        jRadioButton1.setText("학생");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jRadioButton2.setText("교수");

        jRadioButton3.setText("조교");

        jButton1.setText("로그인");

        jButton2.setText("회원가입");

        jLabel3.setText("아이디가 없으신가요?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userId)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPasswordField1))))
                .addGap(65, 65, 65))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * userId, jPasswordField1 필드에 플레이스홀더(힌트 텍스트)를 설정합니다.
     * FocusListener를 사용해 포커스 유무에 따라 힌트를 표시/숨깁니다.
     */
    private void setupPlaceholders() {
        addPlaceholder(userId, "ID");
        addPasswordPlaceholder(jPasswordField1, "Password");
    }

    /**
     * JTextField에 플레이스홀더 동작을 추가합니다.
     *
     * @param field       대상 텍스트 필드
     * @param placeholder 표시할 힌트 문자열
     */
    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
        java.awt.Color hintColor = java.awt.Color.GRAY;
        java.awt.Color normalColor = field.getForeground();

        // 초기 상태: 플레이스홀더 표시
        field.setText(placeholder);
        field.setForeground(hintColor);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(hintColor);
                }
            }
        });
    }

    /**
     * JPasswordField에 플레이스홀더 동작을 추가합니다.
     * 포커스가 없고 비어 있을 때 힌트 텍스트를 표시하며, 이때 에코 문자를 비활성화합니다.
     *
     * @param field       대상 패스워드 필드
     * @param placeholder 표시할 힌트 문자열
     */
    private void addPasswordPlaceholder(javax.swing.JPasswordField field, String placeholder) {
        java.awt.Color hintColor = java.awt.Color.GRAY;
        java.awt.Color normalColor = java.awt.Color.BLACK;
        char defaultEcho = field.getEchoChar();

        // 초기 상태: 플레이스홀더 표시 (에코 문자 해제)
        field.setEchoChar((char) 0);
        field.setText(placeholder);
        field.setForeground(hintColor);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (String.valueOf(field.getPassword()).equals(placeholder)) {
                    field.setEchoChar(defaultEcho);
                    field.setText("");
                    field.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getPassword().length == 0) {
                    field.setEchoChar((char) 0);
                    field.setText(placeholder);
                    field.setForeground(hintColor);
                }
            }
        });
    }

    private void handleLogin(java.awt.event.ActionEvent evt) {
        // 플레이스홀더 상태이면 빈 문자열로 처리
        String id = userId.getText().equals("ID") ? "" : userId.getText().trim();
        // JPasswordField는 getPassword()로 읽고 즉시 보안 처리
        String rawPassword = String.valueOf(jPasswordField1.getPassword());
        String password = rawPassword.equals("Password") ? "" : rawPassword.trim();

        // 역할 선택 여부 확인
        String role = "";
        if (jRadioButton1.isSelected()) {
            role = "STUDENT";
        } else if (jRadioButton2.isSelected()) {
            role = "PROFESSOR";
        } else if (jRadioButton3.isSelected()) {
            role = "ASSISTANT";
        } else {
            // 역할 미선택 시 JOptionPane으로 에러 메시지 표시
            javax.swing.JOptionPane.showMessageDialog(this, "역할을 선택하지 않았습니다.", "오류", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 서버와 소켓 통신하여 로그인 상태 전송 (연결 유지)
        java.net.Socket socket = null;
        try {
            socket = new java.net.Socket("127.0.0.1", 9999);
            java.io.BufferedWriter out = new java.io.BufferedWriter(new java.io.OutputStreamWriter(socket.getOutputStream()));
            java.io.BufferedReader in = new java.io.BufferedReader(new java.io.InputStreamReader(socket.getInputStream()));
            
            // 로그인 요청 전송
            out.write("LOGIN:" + id + "," + password + "," + role + "\n");
            out.flush();
            
            // 서버 응답 대기
            String response = in.readLine();
            
            if ("LOGIN_SUCCESS".equals(response)) {
                javax.swing.JOptionPane.showMessageDialog(this, id + "님 (" + role + ") 로그인 성공!");
                // 로그인 성공 시 연결을 유지합니다. 
                // TODO: 이후 메인 화면(다음 창)을 띄울 때 socket, in, out 객체를 전달하여 통신을 계속 이어가세요.
            } else if ("ALREADY_LOGGED_IN".equals(response)) {
                javax.swing.JOptionPane.showMessageDialog(this, "이미 접속 중인 아이디입니다.", "로그인 실패", javax.swing.JOptionPane.ERROR_MESSAGE);
                socket.close();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "아이디 또는 비밀번호가 일치하지 않습니다.", "로그인 실패", javax.swing.JOptionPane.ERROR_MESSAGE);
                socket.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "서버 연결 실패: " + e.getMessage());
            if (socket != null && !socket.isClosed()) {
                try {
                    socket.close();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables
}
