/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lrr.login;

/**
 *
 * @author seo
 */
public class LoginView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        // 플레이스홀더 설정
        setupPlaceholders();
        // 라디오버튼 그룹 설정 (하나만 선택 가능)
        javax.swing.ButtonGroup roleGroup = new javax.swing.ButtonGroup();
        roleGroup.add(rbStudent); // 학생
        roleGroup.add(rbProfessor); // 교수
        roleGroup.add(rbAssistant); // 조교
    }

    public void addLoginListener(java.awt.event.ActionListener listener) {
        btnLogin.addActionListener(listener);
    }

    public void addRegisterListener(java.awt.event.ActionListener listener) {
        btnRegister.addActionListener(listener);
    }

    public String getId() {
        return idField.getText().equals("ID") ? "" : idField.getText().trim();
    }

    public String getPassword() {
        String rawPassword = String.valueOf(pwField.getPassword());
        return rawPassword.equals("Password") ? "" : rawPassword.trim();
    }

    public String getSelectedRole() {
        if (rbStudent.isSelected()) return "STUDENT";
        if (rbProfessor.isSelected()) return "PROFESSOR";
        if (rbAssistant.isSelected()) return "ASSISTANT";
        return "";
    }

    public void showMessage(String message, String title, int messageType) {
        javax.swing.JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        rbStudent = new javax.swing.JRadioButton();
        rbProfessor = new javax.swing.JRadioButton();
        rbAssistant = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pwField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Lecture Room Reservation");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("User LoginView");

        idField.setToolTipText("ID");
        idField.addActionListener(this::idFieldActionPerformed);

        rbStudent.setText("학생");
        rbStudent.addActionListener(this::rbStudentActionPerformed);

        rbProfessor.setText("교수");

        rbAssistant.setText("조교");

        btnLogin.setText("로그인");

        btnRegister.setText("회원가입");

        jLabel3.setText("아이디가 없으신가요?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAssistant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbProfessor)
                                    .addComponent(rbStudent))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pwField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)))
                .addGap(73, 73, 73))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbAssistant, rbProfessor, rbStudent});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbStudent)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProfessor)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAssistant)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbAssistant, rbProfessor, rbStudent});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void rbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbStudentActionPerformed

    /**
     * idField, pwField 필드에 플레이스홀더(힌트 텍스트)를 설정합니다.
     * FocusListener를 사용해 포커스 유무에 따라 힌트를 표시/숨깁니다.
     */
    private void setupPlaceholders() {
        addPlaceholder(idField, "ID");
        addPasswordPlaceholder(pwField, "Password");
    }

    /**
     * JTextField에 플레이스홀더 동작을 추가합니다.
     *
     * @param field       대상 텍스트 필드
     * @param placeholder 표시할 힌트 문자열
     */
    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
        java.awt.Color hintColor = java.awt.Color.GRAY;
        java.awt.Color normalColor = field.getForeground();

        // 초기 상태: 플레이스홀더 표시
        field.setText(placeholder);
        field.setForeground(hintColor);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(hintColor);
                }
            }
        });
    }

    /**
     * JPasswordField에 플레이스홀더 동작을 추가합니다.
     * 포커스가 없고 비어 있을 때 힌트 텍스트를 표시하며, 이때 에코 문자를 비활성화합니다.
     *
     * @param field       대상 패스워드 필드
     * @param placeholder 표시할 힌트 문자열
     */
    private void addPasswordPlaceholder(javax.swing.JPasswordField field, String placeholder) {
        java.awt.Color hintColor = java.awt.Color.GRAY;
        java.awt.Color normalColor = java.awt.Color.BLACK;
        char defaultEcho = field.getEchoChar();

        // 초기 상태: 플레이스홀더 표시 (에코 문자 해제)
        field.setEchoChar((char) 0);
        field.setText(placeholder);
        field.setForeground(hintColor);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (String.valueOf(field.getPassword()).equals(placeholder)) {
                    field.setEchoChar(defaultEcho);
                    field.setText("");
                    field.setForeground(normalColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getPassword().length == 0) {
                    field.setEchoChar((char) 0);
                    field.setText(placeholder);
                    field.setForeground(hintColor);
                }
            }
        });
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            LoginView view = new LoginView();
            LoginModel model = new LoginModel();
            new LoginController(view, model);
            view.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JRadioButton rbAssistant;
    private javax.swing.JRadioButton rbProfessor;
    private javax.swing.JRadioButton rbStudent;
    // End of variables declaration//GEN-END:variables
}
